default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['CRUD-DE-EVENTOS_DATABASE_USERNAME'] %>
  password: <%= ENV['CRUD-DE-EVENTOS_DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: CRUD-de-Eventos_development

test:
  <<: *default
  database: CRUD-de-Eventos_test

production:
  <<: *default
  database: CRUD-de-Eventos_production
